name: Deploy to EC2
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d "/home/ubuntu/Study-Challenges" ]
          then
            git clone git@github.com:FarrasT-1997/Study-Challenges.git /home/ubuntu/Study-Challenges
          fi
          cd /home/ubuntu/Study-Challenges
          git pull origin master
          docker run --name studychallenges-mysql -e MYSQL_ROOT_PASSWORD=12345 -e MYSQL_DATABASE=study_test -p 3308:3306 -d mysql:latest
          go test -v ./...
          docker stop studychallenges-container
          docker rm studychallenges-container
          docker build -t sc-app:latest .
          docker run --name studychallenges-mysql -e MYSQL_ROOT_PASSWORD=12345 -e MYSQL_DATABASE=study -p 3307:3306 -d mysql:latest
          docker run -d --name studychallenges-container -p 8080:8080 -e "CONNECTION_STRING=root:12345@tcp(172.17.0.1:3307)/study?charset=utf8&parseTime=True&loc=Local" -e "HTTP_PORT=8080" sc-app:latest
